#ifndef TREE_ERROR_TYPES_H_
#define TREE_ERROR_TYPES_H_

typedef enum {
    TREE_VERIFY_SUCCESS = 0,
    TREE_VERIFY_NULL_PTR,
    TREE_VERIFY_INVALID_PARENT,
    TREE_VERIFY_CYCLE_DETECTED
} TreeVerifyResult;

typedef enum {
    TREE_ERROR_NO = 0,
    TREE_ERROR_NULL_PTR,
    TREE_ERROR_ALLOCATION,
    TREE_ERROR_OPENING_FILE,
    TREE_ERROR_INVALID_NODE,
    TREE_ERROR_STRUCTURE,
    TREE_ERROR_FORMAT,
    TREE_ERROR_IO,
    TREE_ERROR_ALREADY_INITIALIZED,

    TREE_ERROR_NO_VARIABLES,
    TREE_ERROR_VARIABLE_TABLE,
    TREE_ERROR_REDEFINITION_VARIABLE,
    TREE_ERROR_VARIABLE_NOT_FOUND,
    TREE_ERROR_VARIABLE_UNDEFINED,
    TREE_ERROR_INVALID_INPUT,
    TREE_ERROR_DIVISION_BY_ZERO,
    TREE_ERROR_UNKNOWN_OPERATION,
    TREE_ERROR_VARIABLE_ALREADY_EXISTS,
    TREE_ERROR_YCHI_MATAN,
    TREE_ERROR_DIFFERENTIATION,
    TREE_ERROR_MEMORY,
    TREE_ERROR_MATH_DOMAIN,
    TREE_ERROR_UNKNOWN_NODE_TYPE
} TreeErrorType;


#endif // TREE_ERROR_TYPES_H_
